apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: towhidk2@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    solvers:
    - selector:
        dnsZones:
          - "smart-techthings.com"
      dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z03494222M86EYPHP0UXN
          # role: arn:aws:iam::235639604932:role/myapp-cluster-cert-manager-role
