apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nodeapp-certificate
spec:
  secretName: nodeapp-tls
  dnsNames:
    - nodeapp.smart-techthings.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer