apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-certificate
spec:
  secretName: tls-wildcard
  dnsNames:
    - smart-techthings.com
    - "*.smart-techthings.com"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer