alertmanager:
  alertmanagerSpec:
    storage: 
    volumeClaimTemplate:
      spec:
        storageClassName: ebs-sc
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        selector: 
          alertmanager: prometheus-kube-prometheus-alertmanager
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ebs-sc
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
          selector:
            matchLabels:
              app: kube-prometheus-stack-prometheus
grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - grafana.smart-techthings.com
    path: /
    tls:
    - secretName: tls-wildcard
      hosts:
      - grafana.smart-techthings.com
