---
- name: Install docker, docker-compose
  hosts: aws_ec2
  become: yes
  gather_facts: False
  tasks:
  - name: Make sure docker is installed
    yum:
      name: docker
      update_cache: yes
      state: present
  - name: Ensure docker-compose is installed
    get_url:
      url: https://github.com/docker/compose/releases/download/v2.3.4/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
      dest: /usr/bin/docker-compose
      mode: +x
  - name: Ensure docker is running
    systemd:
      name: docker
      state: started
      enabled: yes
  - name: Install docker python module
    pip:
      name: 
      - docker
      - docker-compose

- name: Create new linux user
  hosts: aws_ec2
  become: yes
  vars_files:
  - vault.yaml
  tasks:
  - name: Create new linux user
    user:
      name: towhid
      groups: "{{user_groups}}"

- name: Start docker container
  hosts: aws_ec2
  become: yes
  become_user: towhid
  vars_files:
  - vault.yaml
  tasks:
  - name: Docker login
    docker_login:
      registry_url: https://index.docker.io/v1/
      username: towhidk2
      password: "{{docker_password}}"
  - name: Copy docker compose file
    copy: 
      src: ./docker-compose.yaml 
      dest: "/home/towhid/docker-compose.yaml" 
  - name: Update image tag name
    shell:
      cmd: sed -i "s|towhidk2/nodeapp:tag_name|towhidk2/nodeapp:"{{image_tag}}"|g" docker-compose.yaml #update in remote server
      chdir: /home/towhid/
  - name: Start container from compose
    docker_compose:
      project_src: /home/towhid
      state: present

